Completed SSH rule checks and fixes

diff --git a/rules/ssh/ssh_sshd_set_idle_timeout.yaml b/rules/ssh/ssh_sshd_set_idle_timeout.yaml
--- a/rules/ssh/ssh_sshd_set_idle_timeout.yaml
+++ b/rules/ssh/ssh_sshd_set_idle_timeout.yaml
@@ -40,25 +40,15 @@ references:
         - CCE-90811-1
 os_specifics:
   rhel:
-    check: $OS_VALUE
-    result: $OS_VALUE
-    fix: $OS_VALUE
-    '10':
-      severity: medium
-      benchmarks:
-        - disa_stig
-        - nist_800-53r4
-      enforcement_info:
-        - N/A
-      result:
+    enforcement_info:
+      check: sshd -T | grep -q "clientaliveinterval $ODV"; echo $?
+      result: 
         integer: 0
       fix: |
-        [source,bash]
-        ---
         # Remediation is applicable only in certain platforms
         if rpm --quiet -q kernel; then
 
-        sshd_idle_timeout_value=''
+        sshd_idle_timeout_value='$ODV'
 
 
         mkdir -p /etc/ssh/sshd_config.d
@@ -86,18 +76,16 @@ os_specifics:
         else
             >&2 echo 'Remediation is not applicable, nothing was done'
         fi
-
-        ---
+    '10':
+      severity: medium
+      benchmarks:
+        - disa_stig
+        - nist_800-53r4
     '8':
       severity: medium
       benchmarks:
         - disa_stig
         - nist_800-53r4
-      enforcement_info:
-        - N/A
-      result:
-        integer: 0
-      fix: |
         [source,bash]
         ---
         # Remediation is applicable only in certain platforms
@@ -133,11 +121,6 @@ os_specifics:
       benchmarks:
         - disa_stig
         - nist_800-53r4
-      enforcement_info:
-        - N/A
-      result:
-        integer: 0
-      fix: |
         [source,bash]
         ---
         # Remediation is applicable only in certain platforms
@@ -174,19 +157,48 @@ os_specifics:
 
         ---
   ubuntu:
-    check: $OS_VALUE
-    result: $OS_VALUE
-    fix: $OS_VALUE
+    enforcement_info:
+      check: sshd -T | grep -q "clientaliveinterval $ODV"; echo $?
+      result: 
+        integer: 0
+      fix: | 
+        # Remediation is applicable only in certain platforms
+        if dpkg-query --show --showformat='${db:Status-Status}
+        ' 'linux-base' 2>/dev/null | grep -q ^installed; then
+
+        sshd_idle_timeout_value='$ODV'
+
+
+        mkdir -p /etc/ssh/sshd_config.d
+        touch /etc/ssh/sshd_config.d/00-complianceascode-hardening.conf
+        chmod 0600 /etc/ssh/sshd_config.d/00-complianceascode-hardening.conf
+
+        LC_ALL=C sed -i "/^\s*ClientAliveInterval\s\+/Id" "/etc/ssh/sshd_config"
+        LC_ALL=C sed -i "/^\s*ClientAliveInterval\s\+/Id" "/etc/ssh/sshd_config.d"/*.conf
+        if [ -e "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf" ] ; then
+
+            LC_ALL=C sed -i "/^\s*ClientAliveInterval\s\+/Id" "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
+        else
+            touch "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
+        fi
+        # make sure file has newline at the end
+        sed -i -e '$a\' "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
+
+        cp "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf" "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf.bak"
+        # Insert at the beginning of the file
+        printf '%s\n' "ClientAliveInterval $sshd_idle_timeout_value" > "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
+        cat "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf.bak" >> "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
+        # Clean up after ourselves.
+        rm "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf.bak"
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
     '2004':
       severity: medium
       benchmarks:
         - disa_stig
         - nist_800-53r4
-      enforcement_info:
-        - N/A
-      result:
-        integer: 0
-      fix: |
         [source,bash]
         ---
         # Remediation is applicable only in certain platforms
@@ -228,11 +240,6 @@ os_specifics:
       benchmarks:
         - disa_stig
         - nist_800-53r4
-      enforcement_info:
-        - N/A
-      result:
-        integer: 0
-      fix: |
         [source,bash]
         ---
         # Remediation is applicable only in certain platforms
@@ -274,47 +281,16 @@ os_specifics:
       benchmarks:
         - disa_stig
         - nist_800-53r4
-      enforcement_info:
-        - N/A
-      result:
-        integer: 0
-      fix: |
-        [source,bash]
-        ---
-        # Remediation is applicable only in certain platforms
-        if dpkg-query --show --showformat='${db:Status-Status}
-        ' 'linux-base' 2>/dev/null | grep -q ^installed; then
-
-        sshd_idle_timeout_value=''
-
-
-        mkdir -p /etc/ssh/sshd_config.d
-        touch /etc/ssh/sshd_config.d/00-complianceascode-hardening.conf
-        chmod 0600 /etc/ssh/sshd_config.d/00-complianceascode-hardening.conf
-
-        LC_ALL=C sed -i "/^\s*ClientAliveInterval\s\+/Id" "/etc/ssh/sshd_config"
-        LC_ALL=C sed -i "/^\s*ClientAliveInterval\s\+/Id" "/etc/ssh/sshd_config.d"/*.conf
-        if [ -e "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf" ] ; then
-
-            LC_ALL=C sed -i "/^\s*ClientAliveInterval\s\+/Id" "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
-        else
-            touch "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
-        fi
-        # make sure file has newline at the end
-        sed -i -e '$a\' "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
-
-        cp "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf" "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf.bak"
-        # Insert at the beginning of the file
-        printf '%s\n' "ClientAliveInterval $sshd_idle_timeout_value" > "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
-        cat "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf.bak" >> "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
-        # Clean up after ourselves.
-        rm "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf.bak"
-
-        else
-            >&2 echo 'Remediation is not applicable, nothing was done'
-        fi
-
-        ---
+odv:
+  hint:
+    datatype: number
+    description: Number of seconds, e.g. 300
+    validation:
+      min: 30
+  recommended: 300
+  cis_lvl1: 300
+  cis_lvl2: 300
+  stig: 600
 tags:
   - 800-53r4_high
   - 800-53r4_low
diff --git a/rules/ssh/ssh_sshd_set_maxstartups.yaml b/rules/ssh/ssh_sshd_set_maxstartups.yaml
--- a/rules/ssh/ssh_sshd_set_maxstartups.yaml
+++ b/rules/ssh/ssh_sshd_set_maxstartups.yaml
@@ -15,24 +15,15 @@ references:
         - CCE-87872-8
 os_specifics:
   rhel:
-    check: $OS_VALUE
-    result: $OS_VALUE
-    fix: $OS_VALUE
-    '10':
-      severity: medium
-      benchmarks:
-        - N/A
-      enforcement_info:
-        - N/A
-      result:
+    enforcement_info:
+      check: /usr/sbin/sshd -T | /bin/grep -q "maxstartups $ODV"; echo $?
+      result: 
         integer: 0
       fix: |
-        [source,bash]
-        ---
         # Remediation is applicable only in certain platforms
         if rpm --quiet -q kernel; then
 
-        var_sshd_set_maxstartups=''
+        var_sshd_set_maxstartups='$ODV'
 
 
         mkdir -p /etc/ssh/sshd_config.d
@@ -60,17 +51,14 @@ os_specifics:
         else
             >&2 echo 'Remediation is not applicable, nothing was done'
         fi
-
-        ---
+    '10':
+      severity: medium
+      benchmarks:
+        - N/A
     '8':
       severity: medium
       benchmarks:
         - N/A
-      enforcement_info:
-        - N/A
-      result:
-        integer: 0
-      fix: |
         [source,bash]
         ---
         # Remediation is applicable only in certain platforms
@@ -105,11 +93,6 @@ os_specifics:
       severity: medium
       benchmarks:
         - N/A
-      enforcement_info:
-        - N/A
-      result:
-        integer: 0
-      fix: |
         [source,bash]
         ---
         # Remediation is applicable only in certain platforms
@@ -146,63 +129,51 @@ os_specifics:
 
         ---
   ubuntu:
-    check: $OS_VALUE
-    result: $OS_VALUE
-    fix: $OS_VALUE
+    enforcement_info:
+      check: /usr/sbin/sshd -T | /bin/grep -q "maxstartups $ODV"; echo $?
+      result: 
+        integer: 0
+      fix: | 
+          # Remediation is applicable only in certain platforms
+          if dpkg-query --show --showformat='${db:Status-Status}
+          ' 'linux-base' 2>/dev/null | grep -q ^installed; then
+
+          var_sshd_set_maxstartups='$ODV'
+
+
+          mkdir -p /etc/ssh/sshd_config.d
+          touch /etc/ssh/sshd_config.d/00-complianceascode-hardening.conf
+          chmod 0600 /etc/ssh/sshd_config.d/00-complianceascode-hardening.conf
+
+          LC_ALL=C sed -i "/^\s*MaxStartups\s\+/Id" "/etc/ssh/sshd_config"
+          LC_ALL=C sed -i "/^\s*MaxStartups\s\+/Id" "/etc/ssh/sshd_config.d"/*.conf
+          if [ -e "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf" ] ; then
+
+              LC_ALL=C sed -i "/^\s*MaxStartups\s\+/Id" "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
+          else
+              touch "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
+          fi
+          # make sure file has newline at the end
+          sed -i -e '$a\' "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
+
+          cp "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf" "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf.bak"
+          # Insert at the beginning of the file
+          printf '%s\n' "MaxStartups $var_sshd_set_maxstartups" > "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
+          cat "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf.bak" >> "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
+          # Clean up after ourselves.
+          rm "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf.bak"
+
+          else
+              >&2 echo 'Remediation is not applicable, nothing was done'
+          fi
     '2004':
       severity: medium
       benchmarks:
         - N/A
-      enforcement_info:
-        - N/A
-      result:
-        integer: 0
-      fix: |
-        [source,bash]
-        ---
-        # Remediation is applicable only in certain platforms
-        if dpkg-query --show --showformat='${db:Status-Status}
-        ' 'linux-base' 2>/dev/null | grep -q ^installed; then
-
-        var_sshd_set_maxstartups=''
-
-
-        mkdir -p /etc/ssh/sshd_config.d
-        touch /etc/ssh/sshd_config.d/00-complianceascode-hardening.conf
-        chmod 0600 /etc/ssh/sshd_config.d/00-complianceascode-hardening.conf
-
-        LC_ALL=C sed -i "/^\s*MaxStartups\s\+/Id" "/etc/ssh/sshd_config"
-        LC_ALL=C sed -i "/^\s*MaxStartups\s\+/Id" "/etc/ssh/sshd_config.d"/*.conf
-        if [ -e "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf" ] ; then
-
-            LC_ALL=C sed -i "/^\s*MaxStartups\s\+/Id" "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
-        else
-            touch "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
-        fi
-        # make sure file has newline at the end
-        sed -i -e '$a\' "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
-
-        cp "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf" "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf.bak"
-        # Insert at the beginning of the file
-        printf '%s\n' "MaxStartups $var_sshd_set_maxstartups" > "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
-        cat "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf.bak" >> "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf"
-        # Clean up after ourselves.
-        rm "/etc/ssh/sshd_config.d/00-complianceascode-hardening.conf.bak"
-
-        else
-            >&2 echo 'Remediation is not applicable, nothing was done'
-        fi
-
-        ---
     '2204':
       severity: medium
       benchmarks:
         - N/A
-      enforcement_info:
-        - N/A
-      result:
-        integer: 0
-      fix: |
         [source,bash]
         ---
         # Remediation is applicable only in certain platforms
@@ -243,11 +214,6 @@ os_specifics:
       severity: medium
       benchmarks:
         - N/A
-      enforcement_info:
-        - N/A
-      result:
-        integer: 0
-      fix: |
         [source,bash]
         ---
         # Remediation is applicable only in certain platforms
@@ -284,6 +250,13 @@ os_specifics:
         fi
 
         ---
+odv:
+  hint:
+    datatype: string
+    description: Ratio of when to start dropping connections (start), what percent to drop (rate), and the absolute max (full).
+  recommended: "10:30:60"
+  cis_lvl1: "10:30:60"
+  cis_lvl2: "10:30:60"
 tags:
   - cis_lvl1
   - cis_lvl2
