Created rules for gdm_removed, custom_logfile_used, screenlock_enabled

diff --git a/rules/os/os_sudo_custom_logfile_used.yaml b/rules/os/os_sudo_custom_logfile_used.yaml
--- a/rules/os/os_sudo_custom_logfile_used.yaml
+++ b/rules/os/os_sudo_custom_logfile_used.yaml
@@ -1,7 +1,7 @@
-id: os_aide_installed
-title: "The Operating System MUST have AIDE Installed"
+id: os_sudo_custom_logfile_used.yaml
+title: "The Operating System should use a custom log file to monitor sudo usage."
 discussion: |
-  The AIDE package must be installed if it is to be available for integrity checking.
+  A custom log file to monitor sudo usage simplifies auditing and facilitates better incident response.
 check: |
   $OS_VALUE
 result:
@@ -12,22 +12,17 @@ references:
   cce:
     - $OS_VALUE
   cci:
-    - CCI-002696
-    - CCI-002699
-    - CCI-001744
+    - N/A
   800-53r5:
-    - SI-7 
+    - AU-12
   srg:
-    - SRG-OS-000363-GPOS-00150
-    - SRG-OS-000445-GPOS-00199
+    - N/A
   disa_stig:
-    - $OS_VALUE
+    - N/A
 tags:
-  - 800-53r5_moderate
-  - 800-53r5_high
   - client
   - server
-severity: "medium"
+severity: "low"
 os_specifics:
   ubuntu:
     '2004':
@@ -35,22 +30,128 @@ os_specifics:
         cce:
           - N/A
         disa_stig:
-          - UBTU-20-010450
+          - N/A
         check: |
-          /usr/bin/dpkg -l | /usr/bin/grep -c "aide"
+          #! /bin/bash
+          # Checks to see if /etc/sudoers either doesn't contain a sudo log file or a diff path for it
+          # Remediation is applicable only in certain platforms
+          if dpkg-query --show --showformat='${db:Status-Status}\n' 'sudo' 2>/dev/null | grep -q installed; then
+
+          var_sudo_logfile='/var/log/sudo.log'
+
+          # Can we access it?
+          if /usr/sbin/visudo -qcf /etc/sudoers; then
+              if ! grep -P '^[\s]*Defaults[\s]*\blogfile=("(?:\\"|\\\\|[^"\\\n])*"\B|[^"](?:(?:\\,|\\"|\\ |\\\\|[^", \\\n])*)\b)\b.*$' /etc/sudoers; then
+                  # sudoers file doesn't define Option logfile
+                  echo "FAIL"
+              else
+                  # sudoers file defines Option logfile, remediate if appropriate value is not set
+                  if ! grep -P "^[\s]*Defaults.*\blogfile=${var_sudo_logfile}\b.*$" /etc/sudoers; then
+                      echo "FAIL"
+                  else
+                      echo "PASS"
+                  fi
+              fi
         fix: |
-          [source,bash]
-          ---
-          /usr/bin/apt-get -y install aide
-          ---
+          #! /bin/bash
+          # Remediation is applicable only in certain platforms
+          if dpkg-query --show --showformat='${db:Status-Status}\n' 'sudo' 2>/dev/null | grep -q installed; then
+
+          var_sudo_logfile='/var/log/sudo.log'
+
+
+          if /usr/sbin/visudo -qcf /etc/sudoers; then
+              cp /etc/sudoers /etc/sudoers.bak
+              if ! grep -P '^[\s]*Defaults[\s]*\blogfile=("(?:\\"|\\\\|[^"\\\n])*"\B|[^"](?:(?:\\,|\\"|\\ |\\\\|[^", \\\n])*)\b)\b.*$' /etc/sudoers; then
+                  # sudoers file doesn't define Option logfile
+                  echo "Defaults logfile=${var_sudo_logfile}" >> /etc/sudoers
+              else
+                  # sudoers file defines Option logfile, remediate if appropriate value is not set
+                  if ! grep -P "^[\s]*Defaults.*\blogfile=${var_sudo_logfile}\b.*$" /etc/sudoers; then
+                      
+                      escaped_variable=${var_sudo_logfile//$'/'/$'\/'}
+                      sed -Ei "s/(^[\s]*Defaults.*\blogfile=)[-]?.+(\b.*$)/\1$escaped_variable\2/" /etc/sudoers
+                  fi
+              fi
+              
+              # Check validity of sudoers and cleanup bak
+              if /usr/sbin/visudo -qcf /etc/sudoers; then
+                  rm -f /etc/sudoers.bak
+              else
+                  echo "Fail to validate remediated /etc/sudoers, reverting to original file."
+                  mv /etc/sudoers.bak /etc/sudoers
+                  false
+              fi
+          else
+              echo "Skipping remediation, /etc/sudoers failed to validate"
+              false
+          fi
+
+          else
+              >&2 echo 'Remediation is not applicable, nothing was done'
+          fi 
     '2204':
       references:
         cce:
           - N/A
+        disa_stig:
+          - N/A
         check: |
-          /usr/bin/dpkg -l | /usr/bin/grep -c "aide"
+          #! /bin/bash
+          # Checks to see if /etc/sudoers either doesn't contain a sudo log file or a diff path for it
+          # Remediation is applicable only in certain platforms
+          if dpkg-query --show --showformat='${db:Status-Status}\n' 'sudo' 2>/dev/null | grep -q installed; then
+
+          var_sudo_logfile='/var/log/sudo.log'
+
+          # Can we access it?
+          if /usr/sbin/visudo -qcf /etc/sudoers; then
+              if ! grep -P '^[\s]*Defaults[\s]*\blogfile=("(?:\\"|\\\\|[^"\\\n])*"\B|[^"](?:(?:\\,|\\"|\\ |\\\\|[^", \\\n])*)\b)\b.*$' /etc/sudoers; then
+                  # sudoers file doesn't define Option logfile
+                  echo "FAIL"
+              else
+                  # sudoers file defines Option logfile, remediate if appropriate value is not set
+                  if ! grep -P "^[\s]*Defaults.*\blogfile=${var_sudo_logfile}\b.*$" /etc/sudoers; then
+                      echo "FAIL"
+                  else
+                      echo "PASS"
+                  fi
+              fi
         fix: |
-          [source,bash]
-          ---
-          /usr/bin/apt-get -y install aide
-          ---
+          #! /bin/bash
+          # Remediation is applicable only in certain platforms
+          if dpkg-query --show --showformat='${db:Status-Status}\n' 'sudo' 2>/dev/null | grep -q installed; then
+
+          var_sudo_logfile='/var/log/sudo.log'
+
+
+          if /usr/sbin/visudo -qcf /etc/sudoers; then
+              cp /etc/sudoers /etc/sudoers.bak
+              if ! grep -P '^[\s]*Defaults[\s]*\blogfile=("(?:\\"|\\\\|[^"\\\n])*"\B|[^"](?:(?:\\,|\\"|\\ |\\\\|[^", \\\n])*)\b)\b.*$' /etc/sudoers; then
+                  # sudoers file doesn't define Option logfile
+                  echo "Defaults logfile=${var_sudo_logfile}" >> /etc/sudoers
+              else
+                  # sudoers file defines Option logfile, remediate if appropriate value is not set
+                  if ! grep -P "^[\s]*Defaults.*\blogfile=${var_sudo_logfile}\b.*$" /etc/sudoers; then
+                      
+                      escaped_variable=${var_sudo_logfile//$'/'/$'\/'}
+                      sed -Ei "s/(^[\s]*Defaults.*\blogfile=)[-]?.+(\b.*$)/\1$escaped_variable\2/" /etc/sudoers
+                  fi
+              fi
+              
+              # Check validity of sudoers and cleanup bak
+              if /usr/sbin/visudo -qcf /etc/sudoers; then
+                  rm -f /etc/sudoers.bak
+              else
+                  echo "Fail to validate remediated /etc/sudoers, reverting to original file."
+                  mv /etc/sudoers.bak /etc/sudoers
+                  false
+              fi
+          else
+              echo "Skipping remediation, /etc/sudoers failed to validate"
+              false
+          fi
+
+          else
+              >&2 echo 'Remediation is not applicable, nothing was done'
+          fi 
