Migrated old rules to legacy/rules, testrules to rules

diff --git a/rules/audit/audit_audispd_configure_remote_server.yaml b/rules/audit/audit_audispd_configure_remote_server.yaml
--- a/rules/audit/audit_audispd_configure_remote_server.yaml
+++ b/rules/audit/audit_audispd_configure_remote_server.yaml
@@ -1,106 +1,253 @@
 id: audit_audispd_configure_remote_server
-title: "The Operating System should be configured to perform off-loading of audit records"
+title: Configure audispd Plugin To Send Logs To Remote Server
 discussion: |
-  Information stored in one location is vulnerable to accidental or incidental deletion or alteration.
-  Off-loading is a common process in information systems with limited audit storage capacity.
-check: |
-  $OS_VALUE
-result: 
-  integer: 1
-fix: |
-  $OS_VALUE
+  Information stored in one location is vulnerable to accidental or incidental
+  deletion or alteration.Off-loading is a common process in information systems
+  with limited audit storage capacity.
 references:
-  cce:
-    - $OS_VALUE
-  cci: 
-    - CCI-001851
-  800-53r5:
-    - N/A  
-  srg:
-    - SRG-OS-000342-GPOS-00133
-    - SRG-OS-000479-GPOS-00224
-  disa_stig:
-    - UBTU-20-010216
-tags:
-  - 800-53r5_low
-  - 800-53r5_moderate
-  - 800-53r5_high
-  - client
-  - server
-severity: "medium"
+  disa:
+    cci:
+      - CCI-001851
+    srg:
+      - SRG-OS-000342-GPOS-00133
+      - SRG-OS-000479-GPOS-00224
+    disa_stig:
+      '2004':
+        - UBTU-20-010216
+      '2204':
+        - UBTU-22-653020
+  nist:
+    cce:
+      '8':
+        - CCE-80925-1
+      '9':
+        - CCE-89900-5
 os_specifics:
-  ubuntu:
-    '2204':
-      references:
-        cce: 
-          - N/A
-      check: |
-        SERVERSET=$(cat /etc/audit/audisp-remote.conf | grep -e "remote_server \= [a-zA-Z]" | wc -l)
-        ACTIVE=$(cat /etc/audit/plugins.d/au-remote.conf | grep "active = yes" | wc -l)
-        if [[ $SERVERSET -ne 0 ]] && [[ $ACTIVE -ne 0 ]]; then
-           echo "PASS"
-        else
-           echo "FAIL"
-        fi
+  rhel:
+    check: $OS_VALUE
+    result: $OS_VALUE
+    fix: $OS_VALUE
+    '8':
+      severity: medium
+      benchmarks:
+        - disa_stig
+      enforcement_info:
+        check: |
+           [source,bash]
+           ---
+            SERVERSET=$(cat /etc/audit/audisp-remote.conf | grep -e "remote_server \= [a-zA-Z]" | wc -l)
+            ACTIVE=$(cat /etc/audit/plugins.d/au-remote.conf | grep "active = yes" | wc -l)
+            if [[ $SERVERSET -ne 0 ]] && [[ $ACTIVE -ne 0 ]]; then
+              echo 0
+            else
+              echo 1
+            fi
+           ---
+        result:
+           integer: 1
+      result:
+        integer: 0
       fix: |
         [source,bash]
         ---
-          # This will almost certainly NOT work automatically since how would it know the server you'd like to use.
+        # Remediation is applicable only in certain platforms
+        if rpm --quiet -q audit && rpm --quiet -q kernel; then
 
-          
-          # Remediation is applicable only in certain platforms
-          if [ ! -f /.dockerenv ] && [ ! -f /run/.containerenv ] && dpkg-query --show --showformat='${db:Status-Status}\n' 'auditd' 2>/dev/null | grep -q installed; then
-
-          var_audispd_remote_server='logcollector'
+        var_audispd_remote_server=''
 
 
-          AUDITCONFIG=/etc/audit/audisp-remote.conf
+        AUDITCONFIG=/etc/audit/audisp-remote.conf
 
 
-          AUREMOTECONFIG=/etc/audisp/plugins.d/au-remote.conf
 
-          # Strip any search characters in the key arg so that the key can be replaced without
-          # adding any search characters to the config file.
-          stripped_key=$(sed 's/[\^=\$,;+]*//g' <<< "^active")
+        if [ -e "$AUDITCONFIG" ] ; then
 
-          # shellcheck disable=SC2059
-          printf -v formatted_output "%s = %s" "$stripped_key" "yes"
+            LC_ALL=C sed -i "/^\s*remote_server\s*=\s*/Id" "$AUDITCONFIG"
+        else
+            printf '%s\n' "Path '$AUDITCONFIG' wasn't found on this system. Refusing to continue." >&2
+            return 1
+        fi
+        # make sure file has newline at the end
+        sed -i -e '$a\' "$AUDITCONFIG"
 
-          # If the key exists, change it. Otherwise, add it to the config_file.
-          # We search for the key string followed by a word boundary (matched by \>),
-          # so if we search for 'setting', 'setting2' won't match.
-          if LC_ALL=C grep -q -m 1 -i -e "^active\\>" "$AUREMOTECONFIG"; then
-              escaped_formatted_output=$(sed -e 's|/|\\/|g' <<< "$formatted_output")
-              LC_ALL=C sed -i --follow-symlinks "s/^active\\>.*/$escaped_formatted_output/gi" "$AUREMOTECONFIG"
-          else
-              if [[ -s "$AUREMOTECONFIG" ]] && [[ -n "$(tail -c 1 -- "$AUREMOTECONFIG" || true)" ]]; then
-                  LC_ALL=C sed -i --follow-symlinks '$a'\\ "$AUREMOTECONFIG"
-              fi
-              printf '%s\n' "$formatted_output" >> "$AUREMOTECONFIG"
-          fi
+        cp "$AUDITCONFIG" "$AUDITCONFIG.bak"
+        # Insert at the end of the file
+        printf '%s\n' "remote_server = $var_audispd_remote_server" >> "$AUDITCONFIG"
+        # Clean up after ourselves.
+        rm "$AUDITCONFIG.bak"
 
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
 
-          # Strip any search characters in the key arg so that the key can be replaced without
-          # adding any search characters to the config file.
-          stripped_key=$(sed 's/[\^=\$,;+]*//g' <<< "^remote_server")
-
-          # shellcheck disable=SC2059
-          printf -v formatted_output "%s = %s" "$stripped_key" "$var_audispd_remote_server"
-
-          # If the key exists, change it. Otherwise, add it to the config_file.
-          # We search for the key string followed by a word boundary (matched by \>),
-          # so if we search for 'setting', 'setting2' won't match.
-          if LC_ALL=C grep -q -m 1 -i -e "^remote_server\\>" "$AUDITCONFIG"; then
-              escaped_formatted_output=$(sed -e 's|/|\\/|g' <<< "$formatted_output")
-              LC_ALL=C sed -i --follow-symlinks "s/^remote_server\\>.*/$escaped_formatted_output/gi" "$AUDITCONFIG"
-          else
-              if [[ -s "$AUDITCONFIG" ]] && [[ -n "$(tail -c 1 -- "$AUDITCONFIG" || true)" ]]; then
-                  LC_ALL=C sed -i --follow-symlinks '$a'\\ "$AUDITCONFIG"
-              fi
-              printf '%s\n' "$formatted_output" >> "$AUDITCONFIG"
-          fi
-
-          else
-              >&2 echo 'Remediation is not applicable, nothing was done'
-          fi
         ---
+    '9':
+      severity: medium
+      benchmarks:
+        - disa_stig
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
+      fix: |
+        [source,bash]
+        ---
+        # Remediation is applicable only in certain platforms
+        if rpm --quiet -q audit && rpm --quiet -q kernel; then
+
+        var_audispd_remote_server=''
+
+
+        AUDITCONFIG=/etc/audit/audisp-remote.conf
+
+
+
+        if [ -e "$AUDITCONFIG" ] ; then
+
+            LC_ALL=C sed -i "/^\s*remote_server\s*=\s*/Id" "$AUDITCONFIG"
+        else
+            printf '%s\n' "Path '$AUDITCONFIG' wasn't found on this system. Refusing to continue." >&2
+            return 1
+        fi
+        # make sure file has newline at the end
+        sed -i -e '$a\' "$AUDITCONFIG"
+
+        cp "$AUDITCONFIG" "$AUDITCONFIG.bak"
+        # Insert at the end of the file
+        printf '%s\n' "remote_server = $var_audispd_remote_server" >> "$AUDITCONFIG"
+        # Clean up after ourselves.
+        rm "$AUDITCONFIG.bak"
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
+  ubuntu:
+    check: $OS_VALUE
+    result: $OS_VALUE
+    fix: $OS_VALUE
+    '2004':
+      severity: medium
+      benchmarks:
+        - disa_stig
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
+      fix: |
+        [source,bash]
+        ---
+        # Remediation is applicable only in certain platforms
+        if dpkg-query --show --showformat='${db:Status-Status}
+        ' 'linux-base' 2>/dev/null | grep -q ^installed && dpkg-query --show --showformat='${db:Status-Status}\n' 'auditd' 2>/dev/null | grep -q '^installed'; then
+
+        var_audispd_remote_server=''
+
+
+        AUDITCONFIG=/etc/audisp/audisp-remote.conf
+
+
+        AUREMOTECONFIG=/etc/audisp/plugins.d/au-remote.conf
+
+        if [ -e "$AUREMOTECONFIG" ] ; then
+
+            LC_ALL=C sed -i "/^\s*active\s*=\s*/Id" "$AUREMOTECONFIG"
+        else
+            printf '%s\n' "Path '$AUREMOTECONFIG' wasn't found on this system. Refusing to continue." >&2
+            return 1
+        fi
+        # make sure file has newline at the end
+        sed -i -e '$a\' "$AUREMOTECONFIG"
+
+        cp "$AUREMOTECONFIG" "$AUREMOTECONFIG.bak"
+        # Insert at the end of the file
+        printf '%s\n' "active = yes" >> "$AUREMOTECONFIG"
+        # Clean up after ourselves.
+        rm "$AUREMOTECONFIG.bak"
+
+
+        if [ -e "$AUDITCONFIG" ] ; then
+
+            LC_ALL=C sed -i "/^\s*remote_server\s*=\s*/Id" "$AUDITCONFIG"
+        else
+            printf '%s\n' "Path '$AUDITCONFIG' wasn't found on this system. Refusing to continue." >&2
+            return 1
+        fi
+        # make sure file has newline at the end
+        sed -i -e '$a\' "$AUDITCONFIG"
+
+        cp "$AUDITCONFIG" "$AUDITCONFIG.bak"
+        # Insert at the end of the file
+        printf '%s\n' "remote_server = $var_audispd_remote_server" >> "$AUDITCONFIG"
+        # Clean up after ourselves.
+        rm "$AUDITCONFIG.bak"
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
+    '2204':
+      severity: medium
+      benchmarks:
+        - disa_stig
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
+      fix: |
+        [source,bash]
+        ---
+        # Remediation is applicable only in certain platforms
+        if dpkg-query --show --showformat='${db:Status-Status}
+        ' 'linux-base' 2>/dev/null | grep -q ^installed && dpkg-query --show --showformat='${db:Status-Status}\n' 'auditd' 2>/dev/null | grep -q '^installed'; then
+
+        var_audispd_remote_server=''
+
+
+        AUDITCONFIG=/etc/audit/audisp-remote.conf
+
+
+        AUREMOTECONFIG=/etc/audit/plugins.d/au-remote.conf
+
+        if [ -e "$AUREMOTECONFIG" ] ; then
+
+            LC_ALL=C sed -i "/^\s*active\s*=\s*/Id" "$AUREMOTECONFIG"
+        else
+            printf '%s\n' "Path '$AUREMOTECONFIG' wasn't found on this system. Refusing to continue." >&2
+            return 1
+        fi
+        # make sure file has newline at the end
+        sed -i -e '$a\' "$AUREMOTECONFIG"
+
+        cp "$AUREMOTECONFIG" "$AUREMOTECONFIG.bak"
+        # Insert at the end of the file
+        printf '%s\n' "active = yes" >> "$AUREMOTECONFIG"
+        # Clean up after ourselves.
+        rm "$AUREMOTECONFIG.bak"
+
+
+        if [ -e "$AUDITCONFIG" ] ; then
+
+            LC_ALL=C sed -i "/^\s*remote_server\s*=\s*/Id" "$AUDITCONFIG"
+        else
+            printf '%s\n' "Path '$AUDITCONFIG' wasn't found on this system. Refusing to continue." >&2
+            return 1
+        fi
+        # make sure file has newline at the end
+        sed -i -e '$a\' "$AUDITCONFIG"
+
+        cp "$AUDITCONFIG" "$AUDITCONFIG.bak"
+        # Insert at the end of the file
+        printf '%s\n' "remote_server = $var_audispd_remote_server" >> "$AUDITCONFIG"
+        # Clean up after ourselves.
+        rm "$AUDITCONFIG.bak"
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
+tags:
+  - N/A
diff --git a/rules/audit/audit_rules_immutable.yaml b/rules/audit/audit_rules_immutable.yaml
--- a/rules/audit/audit_rules_immutable.yaml
+++ b/rules/audit/audit_rules_immutable.yaml
@@ -1,79 +1,316 @@
 id: audit_rules_immutable
-title: "Auditing controls should be set to be immutable"
+title: Make the auditd Configuration Immutable
 discussion: |
-  Making the audit configuration immutable prevents accidental as well as malicious modification of the audit rules.
-check: |
-  $OS_VALUE
-result:
-  integer: 0
-fix: |
-  $OS_VALUE
+  Making the audit configuration immutable prevents accidental as
+  well as malicious modification of the audit rules, although it may be
+  problematic if legitimate changes are needed during system
+  operation.
 references:
-  cce:
-    - $OS_VALUE
-  cci:
-    - CCI-000162
-    - CCI-000163
-    - CCI-000164
-  800-53r5:
-    - AC-6(9)
-    - CM-6(a)
-  srg:
-    - SRG-OS-000057-GPOS-00027
-    - SRG-OS-000058-GPOS-00028
-    - SRG-OS-000059-GPOS-00029
-  disa_stig:
-    - N/A
-tags:
-  - 800-53r5_low
-  - 800-53r5_moderate
-  - 800-53r5_high
-  - client
-  - server
-severity: "medium"
+  disa:
+    cci:
+      - CCI-000162
+      - CCI-000163
+      - CCI-000164
+    srg:
+      - SRG-OS-000057-GPOS-00027
+      - SRG-OS-000058-GPOS-00028
+      - SRG-OS-000059-GPOS-00029
+    disa_stig:
+      '8':
+        - RHEL-08-030121
+      '9':
+        - RHEL-09-654275
+  nist:
+    800-53r4:
+      - AC-6
+      - CM-6
+    cce:
+      '10':
+        - CCE-89816-3
+      '8':
+        - CCE-80708-1
+      '9':
+        - CCE-83716-1
 os_specifics:
-  ubuntu:
-    '2204':
-      references:
-        cce:
-          - N/A
-      check: |
-        #!/bin/bash
-        IMMUTABLE=$( grep -R -P "\-e 2" /etc/audit/* | wc -l)
-        if [ $IMMUTABLE -e 0 ]; then
-          echo "FAIL"
-        else
-          echo "PASS"
-        fi
+  rhel:
+    check: $OS_VALUE
+    result: $OS_VALUE
+    fix: $OS_VALUE
+    '10':
+      severity: medium
+      benchmarks:
+        - disa_stig
+        - nist_800-53r4
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
       fix: |
         [source,bash]
-          # Remediation is applicable only in certain platforms
-          if [ ! -f /.dockerenv ] && [ ! -f /run/.containerenv ] && dpkg-query --show --showformat='${db:Status-Status}\n' 'auditd' 2>/dev/null | grep -q installed; then
-
-          # Traverse all of:
-          #
-          # /etc/audit/audit.rules,			(for auditctl case)
-          # /etc/audit/rules.d/*.rules			(for augenrules case)
-          #
-          # files to check if '-e .*' setting is present in that '*.rules' file already.
-          # If found, delete such occurrence since auditctl(8) manual page instructs the
-          # '-e 2' rule should be placed as the last rule in the configuration
-          find /etc/audit /etc/audit/rules.d -maxdepth 1 -type f -name '*.rules' -exec sed -i '/-e[[:space:]]\+.*/d' {} ';'
-
-          # Append '-e 2' requirement at the end of both:
-          # * /etc/audit/audit.rules file 		(for auditctl case)
-          # * /etc/audit/rules.d/immutable.rules		(for augenrules case)
-
-          for AUDIT_FILE in "/etc/audit/audit.rules" "/etc/audit/rules.d/immutable.rules"
-          do
-            echo '' >> $AUDIT_FILE
-            echo '# Set the audit.rules configuration immutable per security requirements' >> $AUDIT_FILE
-            echo '# Reboot is required to change audit rules once this setting is applied' >> $AUDIT_FILE
-            echo '-e 2' >> $AUDIT_FILE
-            chmod o-rwx $AUDIT_FILE
-          done
-
-          else
-              >&2 echo 'Remediation is not applicable, nothing was done'
-          fi
         ---
+        # Remediation is applicable only in certain platforms
+        if rpm --quiet -q audit && rpm --quiet -q kernel; then
+
+        # Traverse all of:
+        #
+        # /etc/audit/audit.rules,         (for auditctl case)
+        # /etc/audit/rules.d/*.rules         (for augenrules case)
+        #
+        # files to check if '-e .*' setting is present in that '*.rules' file already.
+        # If found, delete such occurrence since auditctl(8) manual page instructs the
+        # '-e 2' rule should be placed as the last rule in the configuration
+        find /etc/audit /etc/audit/rules.d -maxdepth 1 -type f -name '*.rules' -exec sed -i '/-e[[:space:]]\+.*/d' {} ';'
+
+        # Append '-e 2' requirement at the end of both:
+        # * /etc/audit/audit.rules file       (for auditctl case)
+        # * /etc/audit/rules.d/immutable.rules      (for augenrules case)
+
+        for AUDIT_FILE in "/etc/audit/audit.rules" "/etc/audit/rules.d/immutable.rules"
+        do
+           echo '' >> $AUDIT_FILE
+           echo '# Set the audit.rules configuration immutable per security requirements' >> $AUDIT_FILE
+           echo '# Reboot is required to change audit rules once this setting is applied' >> $AUDIT_FILE
+           echo '-e 2' >> $AUDIT_FILE
+           chmod o-rwx $AUDIT_FILE
+           chmod g-rwx $AUDIT_FILE
+        done
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
+    '8':
+      severity: medium
+      benchmarks:
+        - disa_stig
+        - nist_800-53r4
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
+      fix: |
+        [source,bash]
+        ---
+        # Remediation is applicable only in certain platforms
+        if rpm --quiet -q audit && rpm --quiet -q kernel; then
+
+        # Traverse all of:
+        #
+        # /etc/audit/audit.rules,         (for auditctl case)
+        # /etc/audit/rules.d/*.rules         (for augenrules case)
+        #
+        # files to check if '-e .*' setting is present in that '*.rules' file already.
+        # If found, delete such occurrence since auditctl(8) manual page instructs the
+        # '-e 2' rule should be placed as the last rule in the configuration
+        find /etc/audit /etc/audit/rules.d -maxdepth 1 -type f -name '*.rules' -exec sed -i '/-e[[:space:]]\+.*/d' {} ';'
+
+        # Append '-e 2' requirement at the end of both:
+        # * /etc/audit/audit.rules file       (for auditctl case)
+        # * /etc/audit/rules.d/immutable.rules      (for augenrules case)
+
+        for AUDIT_FILE in "/etc/audit/audit.rules" "/etc/audit/rules.d/immutable.rules"
+        do
+           echo '' >> $AUDIT_FILE
+           echo '# Set the audit.rules configuration immutable per security requirements' >> $AUDIT_FILE
+           echo '# Reboot is required to change audit rules once this setting is applied' >> $AUDIT_FILE
+           echo '-e 2' >> $AUDIT_FILE
+           chmod o-rwx $AUDIT_FILE
+           chmod g-rwx $AUDIT_FILE
+        done
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
+    '9':
+      severity: medium
+      benchmarks:
+        - disa_stig
+        - nist_800-53r4
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
+      fix: |
+        [source,bash]
+        ---
+        # Remediation is applicable only in certain platforms
+        if rpm --quiet -q audit && rpm --quiet -q kernel; then
+
+        # Traverse all of:
+        #
+        # /etc/audit/audit.rules,         (for auditctl case)
+        # /etc/audit/rules.d/*.rules         (for augenrules case)
+        #
+        # files to check if '-e .*' setting is present in that '*.rules' file already.
+        # If found, delete such occurrence since auditctl(8) manual page instructs the
+        # '-e 2' rule should be placed as the last rule in the configuration
+        find /etc/audit /etc/audit/rules.d -maxdepth 1 -type f -name '*.rules' -exec sed -i '/-e[[:space:]]\+.*/d' {} ';'
+
+        # Append '-e 2' requirement at the end of both:
+        # * /etc/audit/audit.rules file       (for auditctl case)
+        # * /etc/audit/rules.d/immutable.rules      (for augenrules case)
+
+        for AUDIT_FILE in "/etc/audit/audit.rules" "/etc/audit/rules.d/immutable.rules"
+        do
+           echo '' >> $AUDIT_FILE
+           echo '# Set the audit.rules configuration immutable per security requirements' >> $AUDIT_FILE
+           echo '# Reboot is required to change audit rules once this setting is applied' >> $AUDIT_FILE
+           echo '-e 2' >> $AUDIT_FILE
+           chmod o-rwx $AUDIT_FILE
+           chmod g-rwx $AUDIT_FILE
+        done
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
+  ubuntu:
+    check: $OS_VALUE
+    result: $OS_VALUE
+    fix: $OS_VALUE
+    '2004':
+      severity: medium
+      benchmarks:
+        - disa_stig
+        - nist_800-53r4
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
+      fix: |
+        [source,bash]
+        ---
+        # Remediation is applicable only in certain platforms
+        if dpkg-query --show --showformat='${db:Status-Status}
+        ' 'linux-base' 2>/dev/null | grep -q ^installed && dpkg-query --show --showformat='${db:Status-Status}\n' 'auditd' 2>/dev/null | grep -q '^installed'; then
+
+        # Traverse all of:
+        #
+        # /etc/audit/audit.rules,         (for auditctl case)
+        # /etc/audit/rules.d/*.rules         (for augenrules case)
+        #
+        # files to check if '-e .*' setting is present in that '*.rules' file already.
+        # If found, delete such occurrence since auditctl(8) manual page instructs the
+        # '-e 2' rule should be placed as the last rule in the configuration
+        find /etc/audit /etc/audit/rules.d -maxdepth 1 -type f -name '*.rules' -exec sed -i '/-e[[:space:]]\+.*/d' {} ';'
+
+        # Append '-e 2' requirement at the end of both:
+        # * /etc/audit/audit.rules file       (for auditctl case)
+        # * /etc/audit/rules.d/immutable.rules      (for augenrules case)
+
+        for AUDIT_FILE in "/etc/audit/audit.rules" "/etc/audit/rules.d/immutable.rules"
+        do
+           echo '' >> $AUDIT_FILE
+           echo '# Set the audit.rules configuration immutable per security requirements' >> $AUDIT_FILE
+           echo '# Reboot is required to change audit rules once this setting is applied' >> $AUDIT_FILE
+           echo '-e 2' >> $AUDIT_FILE
+           chmod o-rwx $AUDIT_FILE
+           chmod g-rwx $AUDIT_FILE
+        done
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
+    '2204':
+      severity: medium
+      benchmarks:
+        - disa_stig
+        - nist_800-53r4
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
+      fix: |
+        [source,bash]
+        ---
+        # Remediation is applicable only in certain platforms
+        if dpkg-query --show --showformat='${db:Status-Status}
+        ' 'linux-base' 2>/dev/null | grep -q ^installed && dpkg-query --show --showformat='${db:Status-Status}\n' 'auditd' 2>/dev/null | grep -q '^installed'; then
+
+        # Traverse all of:
+        #
+        # /etc/audit/audit.rules,         (for auditctl case)
+        # /etc/audit/rules.d/*.rules         (for augenrules case)
+        #
+        # files to check if '-e .*' setting is present in that '*.rules' file already.
+        # If found, delete such occurrence since auditctl(8) manual page instructs the
+        # '-e 2' rule should be placed as the last rule in the configuration
+        find /etc/audit /etc/audit/rules.d -maxdepth 1 -type f -name '*.rules' -exec sed -i '/-e[[:space:]]\+.*/d' {} ';'
+
+        # Append '-e 2' requirement at the end of both:
+        # * /etc/audit/audit.rules file       (for auditctl case)
+        # * /etc/audit/rules.d/immutable.rules      (for augenrules case)
+
+        for AUDIT_FILE in "/etc/audit/audit.rules" "/etc/audit/rules.d/immutable.rules"
+        do
+           echo '' >> $AUDIT_FILE
+           echo '# Set the audit.rules configuration immutable per security requirements' >> $AUDIT_FILE
+           echo '# Reboot is required to change audit rules once this setting is applied' >> $AUDIT_FILE
+           echo '-e 2' >> $AUDIT_FILE
+           chmod o-rwx $AUDIT_FILE
+           chmod g-rwx $AUDIT_FILE
+        done
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
+    '2404':
+      severity: medium
+      benchmarks:
+        - disa_stig
+        - nist_800-53r4
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
+      fix: |
+        [source,bash]
+        ---
+        # Remediation is applicable only in certain platforms
+        if dpkg-query --show --showformat='${db:Status-Status}
+        ' 'linux-base' 2>/dev/null | grep -q ^installed && dpkg-query --show --showformat='${db:Status-Status}\n' 'auditd' 2>/dev/null | grep -q '^installed'; then
+
+        # Traverse all of:
+        #
+        # /etc/audit/audit.rules,         (for auditctl case)
+        # /etc/audit/rules.d/*.rules         (for augenrules case)
+        #
+        # files to check if '-e .*' setting is present in that '*.rules' file already.
+        # If found, delete such occurrence since auditctl(8) manual page instructs the
+        # '-e 2' rule should be placed as the last rule in the configuration
+        find /etc/audit /etc/audit/rules.d -maxdepth 1 -type f -name '*.rules' -exec sed -i '/-e[[:space:]]\+.*/d' {} ';'
+
+        # Append '-e 2' requirement at the end of both:
+        # * /etc/audit/audit.rules file       (for auditctl case)
+        # * /etc/audit/rules.d/immutable.rules      (for augenrules case)
+
+        for AUDIT_FILE in "/etc/audit/audit.rules" "/etc/audit/rules.d/immutable.rules"
+        do
+           echo '' >> $AUDIT_FILE
+           echo '# Set the audit.rules configuration immutable per security requirements' >> $AUDIT_FILE
+           echo '# Reboot is required to change audit rules once this setting is applied' >> $AUDIT_FILE
+           echo '-e 2' >> $AUDIT_FILE
+           chmod o-rwx $AUDIT_FILE
+           chmod g-rwx $AUDIT_FILE
+        done
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
+tags:
+  - 800-53r4_high
+  - 800-53r4_low
+  - 800-53r4_moderate
+  - cis_lvl2
+  - client
+  - server
diff --git a/rules/os/os_sudo_custom_logfile_used.yaml b/rules/os/os_sudo_custom_logfile_used.yaml
--- a/rules/os/os_sudo_custom_logfile_used.yaml
+++ b/rules/os/os_sudo_custom_logfile_used.yaml
@@ -1,157 +1,320 @@
-id: os_sudo_custom_logfile_used.yaml
-title: "The Operating System should use a custom log file to monitor sudo usage."
-discussion: |
-  A custom log file to monitor sudo usage simplifies auditing and facilitates better incident response.
-check: |
-  $OS_VALUE
-result:
-  integer: 1
-fix: |
-  $OS_VALUE
+id: os_sudo_custom_logfile_used
+title: Ensure Sudo Logfile Exists - sudo logfile
+discussion: A sudo log file simplifies auditing of sudo commands.
 references:
-  cce:
-    - $OS_VALUE
-  cci:
-    - N/A
-  800-53r5:
-    - AU-12
-  srg:
-    - N/A
-  disa_stig:
-    - N/A
+  nist:
+    cce:
+      '10':
+        - CCE-89611-8
+      '8':
+        - CCE-83601-5
+      '9':
+        - CCE-83527-2
+os_specifics:
+  rhel:
+    check: $OS_VALUE
+    result: $OS_VALUE
+    fix: $OS_VALUE
+    '10':
+      severity: low
+      benchmarks:
+        - N/A
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
+      fix: |
+        [source,bash]
+        ---
+        # Remediation is applicable only in certain platforms
+        if rpm --quiet -q sudo; then
+
+        var_sudo_logfile=''
+
+
+        if /usr/sbin/visudo -qcf /etc/sudoers; then
+            cp /etc/sudoers /etc/sudoers.bak
+            if ! grep -P '^[\s]*Defaults[\s]*\blogfile\s*=\s*(?:"?([^",\s]+)"?)\b.*$' /etc/sudoers; then
+                # sudoers file doesn't define Option logfile
+                echo "Defaults logfile=${var_sudo_logfile}" >> /etc/sudoers
+            else
+                # sudoers file defines Option logfile, remediate if appropriate value is not set
+                if ! grep -P "^[\s]*Defaults.*\blogfile=${var_sudo_logfile}\b.*$" /etc/sudoers; then
+
+                    escaped_variable=${var_sudo_logfile//$'/'/$'\/'}
+                    sed -Ei "s/(^[\s]*Defaults.*\blogfile=)[-]?.+(\b.*$)/\1$escaped_variable\2/" /etc/sudoers
+                fi
+            fi
+
+            # Check validity of sudoers and cleanup bak
+            if /usr/sbin/visudo -qcf /etc/sudoers; then
+                rm -f /etc/sudoers.bak
+            else
+                echo "Fail to validate remediated /etc/sudoers, reverting to original file."
+                mv /etc/sudoers.bak /etc/sudoers
+                false
+            fi
+        else
+            echo "Skipping remediation, /etc/sudoers failed to validate"
+            false
+        fi
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
+    '8':
+      severity: low
+      benchmarks:
+        - N/A
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
+      fix: |
+        [source,bash]
+        ---
+        # Remediation is applicable only in certain platforms
+        if rpm --quiet -q sudo; then
+
+        var_sudo_logfile=''
+
+
+        if /usr/sbin/visudo -qcf /etc/sudoers; then
+            cp /etc/sudoers /etc/sudoers.bak
+            if ! grep -P '^[\s]*Defaults[\s]*\blogfile\s*=\s*(?:"?([^",\s]+)"?)\b.*$' /etc/sudoers; then
+                # sudoers file doesn't define Option logfile
+                echo "Defaults logfile=${var_sudo_logfile}" >> /etc/sudoers
+            else
+                # sudoers file defines Option logfile, remediate if appropriate value is not set
+                if ! grep -P "^[\s]*Defaults.*\blogfile=${var_sudo_logfile}\b.*$" /etc/sudoers; then
+
+                    escaped_variable=${var_sudo_logfile//$'/'/$'\/'}
+                    sed -Ei "s/(^[\s]*Defaults.*\blogfile=)[-]?.+(\b.*$)/\1$escaped_variable\2/" /etc/sudoers
+                fi
+            fi
+
+            # Check validity of sudoers and cleanup bak
+            if /usr/sbin/visudo -qcf /etc/sudoers; then
+                rm -f /etc/sudoers.bak
+            else
+                echo "Fail to validate remediated /etc/sudoers, reverting to original file."
+                mv /etc/sudoers.bak /etc/sudoers
+                false
+            fi
+        else
+            echo "Skipping remediation, /etc/sudoers failed to validate"
+            false
+        fi
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
+    '9':
+      severity: low
+      benchmarks:
+        - N/A
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
+      fix: |
+        [source,bash]
+        ---
+        # Remediation is applicable only in certain platforms
+        if rpm --quiet -q sudo; then
+
+        var_sudo_logfile=''
+
+
+        if /usr/sbin/visudo -qcf /etc/sudoers; then
+            cp /etc/sudoers /etc/sudoers.bak
+            if ! grep -P '^[\s]*Defaults[\s]*\blogfile\s*=\s*(?:"?([^",\s]+)"?)\b.*$' /etc/sudoers; then
+                # sudoers file doesn't define Option logfile
+                echo "Defaults logfile=${var_sudo_logfile}" >> /etc/sudoers
+            else
+                # sudoers file defines Option logfile, remediate if appropriate value is not set
+                if ! grep -P "^[\s]*Defaults.*\blogfile=${var_sudo_logfile}\b.*$" /etc/sudoers; then
+
+                    escaped_variable=${var_sudo_logfile//$'/'/$'\/'}
+                    sed -Ei "s/(^[\s]*Defaults.*\blogfile=)[-]?.+(\b.*$)/\1$escaped_variable\2/" /etc/sudoers
+                fi
+            fi
+
+            # Check validity of sudoers and cleanup bak
+            if /usr/sbin/visudo -qcf /etc/sudoers; then
+                rm -f /etc/sudoers.bak
+            else
+                echo "Fail to validate remediated /etc/sudoers, reverting to original file."
+                mv /etc/sudoers.bak /etc/sudoers
+                false
+            fi
+        else
+            echo "Skipping remediation, /etc/sudoers failed to validate"
+            false
+        fi
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
+  ubuntu:
+    check: $OS_VALUE
+    result: $OS_VALUE
+    fix: $OS_VALUE
+    '2004':
+      severity: low
+      benchmarks:
+        - N/A
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
+      fix: |
+        [source,bash]
+        ---
+        # Remediation is applicable only in certain platforms
+        if dpkg-query --show --showformat='${db:Status-Status}\n' 'sudo' 2>/dev/null | grep -q '^installed'; then
+
+        var_sudo_logfile=''
+
+
+        if /usr/sbin/visudo -qcf /etc/sudoers; then
+            cp /etc/sudoers /etc/sudoers.bak
+            if ! grep -P '^[\s]*Defaults[\s]*\blogfile\s*=\s*(?:"?([^",\s]+)"?)\b.*$' /etc/sudoers; then
+                # sudoers file doesn't define Option logfile
+                echo "Defaults logfile=${var_sudo_logfile}" >> /etc/sudoers
+            else
+                # sudoers file defines Option logfile, remediate if appropriate value is not set
+                if ! grep -P "^[\s]*Defaults.*\blogfile=${var_sudo_logfile}\b.*$" /etc/sudoers; then
+
+                    escaped_variable=${var_sudo_logfile//$'/'/$'\/'}
+                    sed -Ei "s/(^[\s]*Defaults.*\blogfile=)[-]?.+(\b.*$)/\1$escaped_variable\2/" /etc/sudoers
+                fi
+            fi
+
+            # Check validity of sudoers and cleanup bak
+            if /usr/sbin/visudo -qcf /etc/sudoers; then
+                rm -f /etc/sudoers.bak
+            else
+                echo "Fail to validate remediated /etc/sudoers, reverting to original file."
+                mv /etc/sudoers.bak /etc/sudoers
+                false
+            fi
+        else
+            echo "Skipping remediation, /etc/sudoers failed to validate"
+            false
+        fi
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
+    '2204':
+      severity: low
+      benchmarks:
+        - N/A
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
+      fix: |
+        [source,bash]
+        ---
+        # Remediation is applicable only in certain platforms
+        if dpkg-query --show --showformat='${db:Status-Status}\n' 'sudo' 2>/dev/null | grep -q '^installed'; then
+
+        var_sudo_logfile=''
+
+
+        if /usr/sbin/visudo -qcf /etc/sudoers; then
+            cp /etc/sudoers /etc/sudoers.bak
+            if ! grep -P '^[\s]*Defaults[\s]*\blogfile\s*=\s*(?:"?([^",\s]+)"?)\b.*$' /etc/sudoers; then
+                # sudoers file doesn't define Option logfile
+                echo "Defaults logfile=${var_sudo_logfile}" >> /etc/sudoers
+            else
+                # sudoers file defines Option logfile, remediate if appropriate value is not set
+                if ! grep -P "^[\s]*Defaults.*\blogfile=${var_sudo_logfile}\b.*$" /etc/sudoers; then
+
+                    escaped_variable=${var_sudo_logfile//$'/'/$'\/'}
+                    sed -Ei "s/(^[\s]*Defaults.*\blogfile=)[-]?.+(\b.*$)/\1$escaped_variable\2/" /etc/sudoers
+                fi
+            fi
+
+            # Check validity of sudoers and cleanup bak
+            if /usr/sbin/visudo -qcf /etc/sudoers; then
+                rm -f /etc/sudoers.bak
+            else
+                echo "Fail to validate remediated /etc/sudoers, reverting to original file."
+                mv /etc/sudoers.bak /etc/sudoers
+                false
+            fi
+        else
+            echo "Skipping remediation, /etc/sudoers failed to validate"
+            false
+        fi
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
+    '2404':
+      severity: low
+      benchmarks:
+        - N/A
+      enforcement_info:
+        - N/A
+      result:
+        integer: 0
+      fix: |
+        [source,bash]
+        ---
+        # Remediation is applicable only in certain platforms
+        if dpkg-query --show --showformat='${db:Status-Status}\n' 'sudo' 2>/dev/null | grep -q '^installed'; then
+
+        var_sudo_logfile=''
+
+
+        if /usr/sbin/visudo -qcf /etc/sudoers; then
+            cp /etc/sudoers /etc/sudoers.bak
+            if ! grep -P '^[\s]*Defaults[\s]*\blogfile\s*=\s*(?:"?([^",\s]+)"?)\b.*$' /etc/sudoers; then
+                # sudoers file doesn't define Option logfile
+                echo "Defaults logfile=${var_sudo_logfile}" >> /etc/sudoers
+            else
+                # sudoers file defines Option logfile, remediate if appropriate value is not set
+                if ! grep -P "^[\s]*Defaults.*\blogfile=${var_sudo_logfile}\b.*$" /etc/sudoers; then
+
+                    escaped_variable=${var_sudo_logfile//$'/'/$'\/'}
+                    sed -Ei "s/(^[\s]*Defaults.*\blogfile=)[-]?.+(\b.*$)/\1$escaped_variable\2/" /etc/sudoers
+                fi
+            fi
+
+            # Check validity of sudoers and cleanup bak
+            if /usr/sbin/visudo -qcf /etc/sudoers; then
+                rm -f /etc/sudoers.bak
+            else
+                echo "Fail to validate remediated /etc/sudoers, reverting to original file."
+                mv /etc/sudoers.bak /etc/sudoers
+                false
+            fi
+        else
+            echo "Skipping remediation, /etc/sudoers failed to validate"
+            false
+        fi
+
+        else
+            >&2 echo 'Remediation is not applicable, nothing was done'
+        fi
+
+        ---
 tags:
+  - cis_lvl1
+  - cis_lvl2
   - client
   - server
-severity: "low"
-os_specifics:
-  ubuntu:
-    '2004':
-      references:
-        cce:
-          - N/A
-        disa_stig:
-          - N/A
-        check: |
-          #! /bin/bash
-          # Checks to see if /etc/sudoers either doesn't contain a sudo log file or a diff path for it
-          # Remediation is applicable only in certain platforms
-          if dpkg-query --show --showformat='${db:Status-Status}\n' 'sudo' 2>/dev/null | grep -q installed; then
-
-          var_sudo_logfile='/var/log/sudo.log'
-
-          # Can we access it?
-          if /usr/sbin/visudo -qcf /etc/sudoers; then
-              if ! grep -P '^[\s]*Defaults[\s]*\blogfile=("(?:\\"|\\\\|[^"\\\n])*"\B|[^"](?:(?:\\,|\\"|\\ |\\\\|[^", \\\n])*)\b)\b.*$' /etc/sudoers; then
-                  # sudoers file doesn't define Option logfile
-                  echo "FAIL"
-              else
-                  # sudoers file defines Option logfile, remediate if appropriate value is not set
-                  if ! grep -P "^[\s]*Defaults.*\blogfile=${var_sudo_logfile}\b.*$" /etc/sudoers; then
-                      echo "FAIL"
-                  else
-                      echo "PASS"
-                  fi
-              fi
-        fix: |
-          #! /bin/bash
-          # Remediation is applicable only in certain platforms
-          if dpkg-query --show --showformat='${db:Status-Status}\n' 'sudo' 2>/dev/null | grep -q installed; then
-
-          var_sudo_logfile='/var/log/sudo.log'
-
-
-          if /usr/sbin/visudo -qcf /etc/sudoers; then
-              cp /etc/sudoers /etc/sudoers.bak
-              if ! grep -P '^[\s]*Defaults[\s]*\blogfile=("(?:\\"|\\\\|[^"\\\n])*"\B|[^"](?:(?:\\,|\\"|\\ |\\\\|[^", \\\n])*)\b)\b.*$' /etc/sudoers; then
-                  # sudoers file doesn't define Option logfile
-                  echo "Defaults logfile=${var_sudo_logfile}" >> /etc/sudoers
-              else
-                  # sudoers file defines Option logfile, remediate if appropriate value is not set
-                  if ! grep -P "^[\s]*Defaults.*\blogfile=${var_sudo_logfile}\b.*$" /etc/sudoers; then
-                      
-                      escaped_variable=${var_sudo_logfile//$'/'/$'\/'}
-                      sed -Ei "s/(^[\s]*Defaults.*\blogfile=)[-]?.+(\b.*$)/\1$escaped_variable\2/" /etc/sudoers
-                  fi
-              fi
-              
-              # Check validity of sudoers and cleanup bak
-              if /usr/sbin/visudo -qcf /etc/sudoers; then
-                  rm -f /etc/sudoers.bak
-              else
-                  echo "Fail to validate remediated /etc/sudoers, reverting to original file."
-                  mv /etc/sudoers.bak /etc/sudoers
-                  false
-              fi
-          else
-              echo "Skipping remediation, /etc/sudoers failed to validate"
-              false
-          fi
-
-          else
-              >&2 echo 'Remediation is not applicable, nothing was done'
-          fi 
-    '2204':
-      references:
-        cce:
-          - N/A
-        disa_stig:
-          - N/A
-        check: |
-          #! /bin/bash
-          # Checks to see if /etc/sudoers either doesn't contain a sudo log file or a diff path for it
-          # Remediation is applicable only in certain platforms
-          if dpkg-query --show --showformat='${db:Status-Status}\n' 'sudo' 2>/dev/null | grep -q installed; then
-
-          var_sudo_logfile='/var/log/sudo.log'
-
-          # Can we access it?
-          if /usr/sbin/visudo -qcf /etc/sudoers; then
-              if ! grep -P '^[\s]*Defaults[\s]*\blogfile=("(?:\\"|\\\\|[^"\\\n])*"\B|[^"](?:(?:\\,|\\"|\\ |\\\\|[^", \\\n])*)\b)\b.*$' /etc/sudoers; then
-                  # sudoers file doesn't define Option logfile
-                  echo "FAIL"
-              else
-                  # sudoers file defines Option logfile, remediate if appropriate value is not set
-                  if ! grep -P "^[\s]*Defaults.*\blogfile=${var_sudo_logfile}\b.*$" /etc/sudoers; then
-                      echo "FAIL"
-                  else
-                      echo "PASS"
-                  fi
-              fi
-        fix: |
-          #! /bin/bash
-          # Remediation is applicable only in certain platforms
-          if dpkg-query --show --showformat='${db:Status-Status}\n' 'sudo' 2>/dev/null | grep -q installed; then
-
-          var_sudo_logfile='/var/log/sudo.log'
-
-
-          if /usr/sbin/visudo -qcf /etc/sudoers; then
-              cp /etc/sudoers /etc/sudoers.bak
-              if ! grep -P '^[\s]*Defaults[\s]*\blogfile=("(?:\\"|\\\\|[^"\\\n])*"\B|[^"](?:(?:\\,|\\"|\\ |\\\\|[^", \\\n])*)\b)\b.*$' /etc/sudoers; then
-                  # sudoers file doesn't define Option logfile
-                  echo "Defaults logfile=${var_sudo_logfile}" >> /etc/sudoers
-              else
-                  # sudoers file defines Option logfile, remediate if appropriate value is not set
-                  if ! grep -P "^[\s]*Defaults.*\blogfile=${var_sudo_logfile}\b.*$" /etc/sudoers; then
-                      
-                      escaped_variable=${var_sudo_logfile//$'/'/$'\/'}
-                      sed -Ei "s/(^[\s]*Defaults.*\blogfile=)[-]?.+(\b.*$)/\1$escaped_variable\2/" /etc/sudoers
-                  fi
-              fi
-              
-              # Check validity of sudoers and cleanup bak
-              if /usr/sbin/visudo -qcf /etc/sudoers; then
-                  rm -f /etc/sudoers.bak
-              else
-                  echo "Fail to validate remediated /etc/sudoers, reverting to original file."
-                  mv /etc/sudoers.bak /etc/sudoers
-                  false
-              fi
-          else
-              echo "Skipping remediation, /etc/sudoers failed to validate"
-              false
-          fi
-
-          else
-              >&2 echo 'Remediation is not applicable, nothing was done'
-          fi 
